### ISSUE TITLE
IntList: funzione length

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#1]
Bisogna implementare la funzione length() che restituisce la lunghezza della lista

**Comment by TeoColuccio** [comment]
La lunghezza del vettore è 16, quale lunghezza deve ritornare?

2016-01-20 20:44 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
non ci sono sempre 16 elementi nella llista

**Comment by TeoColuccio** [comment]
Credo di aver capito

2016-01-21 21:38 GMT+01:00 Fabio Z Tessitore notifications@github.com:
