### ISSUE TITLE
board

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#11]
creare la struttura dati board.
al momento conterrà un vettore di puntatori a Tile e una intlist delle posizioni libere

**Comment by TeoColuccio** [comment]
Fatto e ho scritto pure i prototipi di set e get

2016-01-31 18:49 GMT+00:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Puoi cominciare a fare la board_init
Deve mettere tutti i puntatori a NULL e impostare la lista delle posizioni
libere

Il mercoledì 3 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by FabioZTessitore** [comment]
La board deve contenere una lista delle posizioni libere, non un intero
