### ISSUE TITLE
board_init

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#13]

**Comment by TeoColuccio** [comment]
Fatto

2016-02-03 18:03 GMT+00:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
modificare in base alle indicazioni della issue #11

**Comment by TeoColuccio** [comment]
Ah e quindi come la imposto la lista?

2016-02-03 18:10 GMT+00:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
non hai creato un modulo apposta?

**Comment by TeoColuccio** [comment]
L'ho messo come un puntatore a intlist, va bene?

2016-02-03 18:17 GMT+00:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
per me può anche andar bene, ma devi farlo come si deve. Se metti un puntatore non c'è la lista ... ricordi?

**Comment by TeoColuccio** [comment]
No non ho capito

Il mercoledì 3 febbraio 2016, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
Quando crei una `Board` (vedi il file main.c) viene creato un puntatore alla `IntList` ... ma la `IntList` non c'è!!!

**Comment by TeoColuccio** [comment]
No non ho capito bene il concetto, magari domani me lo spiegate di
persona..
Ma se gli cambiassi il tipo a una normale intlist come le uso le funzioni
che accettano un puntatore ad intlist?

2016-02-03 22:07 GMT+00:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Un puntatore è semplicemente una variabile che contiene un indirizzo

Il giovedì 4 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Sto cercando di tornare all'opzione più facile, però ho problemi con la
intlist_clear() in board_init(): la clear vuole un puntatore ad una intlist
ora forse non ricordo bene la sintassi per passare un indirizzo...
intlist_clear(&(b->pos_free));

Il giorno 4 febbraio 2016 16:27, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
si, è questa

**Comment by TeoColuccio** [comment]
Bene andiamo avanti

2016-02-05 20:49 GMT+00:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
sei sicuro che vada bene così? ti compila?

**Comment by TeoColuccio** [comment]
A me va bene ahah

2016-02-05 21:17 GMT+00:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Il giorno 5 febbraio 2016 21:30, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
ma non dire sciocchezze

**Comment by TeoColuccio** [comment]
Si su un altro pc mi esce l'errore, forse era un bug di make che faceva
cilecca.. comunque non so interpretare l'errore

2016-02-05 22:37 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
se dico che "hai aggiustato da una parte e non dall'altra" riesci a capire?

**Comment by TeoColuccio** [comment]
Sì ma mi ha ingannato comunque il make... avete visto la foto?

2016-02-06 8:20 GMT+00:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
quando viene inizializzata la board bisogna impostare la lista delle posizioni libere. Al momento hai una lista vuota

**Comment by TeoColuccio** [comment]
E questo non fa parte di init

2016-02-06 19:35 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
perché no? la lista delle posizioni libere è un attributo della board. Quindi quando ne creo una la lista deve essere sincronizzata

**Comment by TeoColuccio** [comment]
Era una domanda (scontata ovviamente).. Comunque questo non fa parte di
board_init() al momento della chiamata ad intlist_clear()?

Il giorno 6 febbraio 2016 19:32, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
intlist_clear() come dice il nome stesso della funzione ... pulisce

Dopo aver fatto pulizia nella lista bisogna metterci gli indici delle caselle vuote

**Comment by TeoColuccio** [comment]
Una funzione che vede le caselle vuote dovrebbe essere la intlist_clear

Il giorno 6 febbraio 2016 20:36, Fabio Z Tessitore <notifications@github.com

**Comment by TeoColuccio** [comment]
Però non capisco ora che altro ci vuole per impostare questi indici

Il giorno 7 febbraio 2016 12:07, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Non ci siamo capiti. Freepos è la lista delle posizioni libere sulla
scacchiera. Se dopo board_init provi a farne una stampa con intlist_dump
cosa esce? E invece cosa dovrebbe uscire?

Il domenica 7 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Ora pos_free è sincronizzata con la board

Il giorno 7 febbraio 2016 12:13, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
mi fai cadere le braccia!!!
ma dove? cosa?

**Comment by TeoColuccio** [comment]
Ahah allora nel main la intlist_dump() stampa quei due valori che ho
messo...

2016-02-07 21:49 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma che c'entra il main. Quello lo stai usando per fare dei test.

**Comment by TeoColuccio** [comment]
Mo non devo fare un test? per vedere cosa esce se metto intlist_dump() dopo
board_init()

2016-02-07 22:29 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
nell'ultima versione che hai pubblicato, alla fine della funzione board_init() c'è una chiamata a intlist_dump() che stampa i valori contenuti in una intlist.

**Comment by TeoColuccio** [comment]
E non va bene?

Il lunedì 8 febbraio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Ma lo vedi anche tu che non esce niente no? Significa che la lista è vuota.
Ma quando la scacchiera viene creata sono libere tutte le posizioni

Il martedì 9 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Io sapendo che era vuota pensavo fosse normaleil fatto che con il dump non
uscisse nulla ahah mo ho capito invece il senso

Il giorno 9 febbraio 2016 11:27, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
per ora la chiudo, poi riapriamo per ulteriori modifiche e aggiustamenti
