### ISSUE TITLE
board_dump

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#14]
crea la funzione board_dump che stampa tutte le info della board (le celle, la lista delle posizioni libere, il numero di posizioni libere)

ps. togli la intlist_dump da board_init()

**Comment by TeoColuccio** [comment]
Per il numero di posizioni libere non mi sembra abbiamo qualche funzione a
disposizione

2016-02-11 19:41 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Per stampare la lista ho usato semplicemente la intlist_dump(), ma potevo
anche usare la intlist_get() all'interno d'un ciclo

Il giorno 11 febbraio 2016 20:57, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
un po' di ingegno

2016-02-11 20:57 GMT+01:00 Teodoro notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma visto che già ce l'hai meglio delegare a lei. Intlist_dump si suppone
che conosca meglio come è fatta una intlist

Il giorno 11 febbraio 2016 21:15, Fabio Z Tessitore <
fabioztessitore@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
L'utilizzo della variabile celle_libere è in più, però ci può stare come controllo per il valore stampato da intlist_len.

Invece non vedo nessuna stampa delle celle

**Comment by TeoColuccio** [comment]
Per celle intendete il numero di celle (in totale) o la lista delle celle?

Il giorno 11 febbraio 2016 21:19, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
proprio le celle, immagina che tu abbia aggiunto delle tessere alla
tabella. Come fai a controllare che sia tutto ok?
Allora la board_dump deve stampare tutte le info sulla board, non solo gli
indici delle celle libere

Il giorno 11 febbraio 2016 21:23, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
La intlist_dump non mi stampa proprio i valori delle celle?

Il giorno 11 febbraio 2016 21:24, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
la intlist_dump ti stampa il contenuto della lista freepos.
La lista freepos contiene gli indici delle celle libere

Il giorno 11 febbraio 2016 21:27, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Forse ho  capito: devo stampare le tile, se ci sono, in ogni singola cella?

Il giorno 11 febbraio 2016 21:28, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
eh

Il giorno 11 febbraio 2016 21:32, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Visto che tile_ptr è un vettore di puntatori a tile, come lo passo a
tile_dump() che vuole un puntatore a tile?
Inoltre creerei una funzione intlist_pos_free() che stampa il numero di
celle libere, così da riutilizzare il codice

Il giorno 11 febbraio 2016 21:39, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
intlist_posfree non ti serve, hai intlist_dump

riguardo a tileptr non credo di aver capito che intendi. Tieni presente che
tile_dump vuole l'indirizzo di una tile per poterla stampare

Il giorno 11 febbraio 2016 21:46, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Avete capito bene, quello è il problema, come ce lo passo un indirizzo di
tile?
Sto provando così: (&(b->pos_free) ma non va bene

Il giorno 11 febbraio 2016 21:48, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
ma che c'entra posfree con le tile?

Il giorno 11 febbraio 2016 21:51, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Sì scusate, il vettore di puntatori a tile ptr_tile

Il giorno 11 febbraio 2016 21:51, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
passare una tile alla volta ti crea problemi?

**Comment by TeoColuccio** [comment]
Quando avete detto:

L'utilizzo della variabile celle_libere è in più, però ci può stare come
controllo per il valore stampato da intlist_len.

Invece non vedo nessuna stampa delle celle "...

Come mai è in più, potevo riutilizzare i?

Il giorno 11 febbraio 2016 21:54, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
ahe, ma non leggi?
"come controllo per il valore stampato da intlist_len"

Il giorno 11 febbraio 2016 21:59, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ahah ma comunque come passo l'indirizzo del singolo elemento? Sto facendo:
tile_dump(&(b->ptr_tile[index])

Il giorno 11 febbraio 2016 22:01, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
b->ptr_tile[index] di che tipo è?

Il giorno 11 febbraio 2016 22:09, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Puntatore b che punta al vettore di puntatore di tile, in questo caso di
indice index

Il giorno 11 febbraio 2016 22:10, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
eeeeh quante cose inutili ...
b->ptr_tile[index] è una variabile. Di che tipo?

Il giorno 11 febbraio 2016 22:11, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Puntatore

Il giorno 11 febbraio 2016 22:12, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
O vettore di puntatori a tile

Il giorno 11 febbraio 2016 22:14, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
hahaha

allora

b è un puntaore a board e non ci interessa
b->ptr_tile è un vettore di puntatori a tile
b->ptr_tile[index] è un elemento di questo vettore, quindi di che tipo è?

Il giorno 11 febbraio 2016 22:15, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ah un puntatore a tile

Il giorno 11 febbraio 2016 22:17, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
aaahhh lavora

Il giorno 11 febbraio 2016 22:18, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ok mo sì

Il giorno 11 febbraio 2016 22:18, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ho fatto, comunque sarebbe più ordinato se, nella stampa, mettesse il
valore delle celle affianco al proprio indice: 4  NULL

Il giorno 11 febbraio 2016 22:21, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
e perchè non lo fai?

Il giorno 11 febbraio 2016 22:36, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ok ma  intlist_dump  non la posso usare perchè stampa gli indici tutti
insieme

Il giorno 11 febbraio 2016 22:38, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
per fare quest'ultima stampa no. Ma d'altra parte gli indici mica li vuoi
stampare solo sulle celle libere

Il giorno 11 febbraio 2016 22:59, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
No li devo stampare tutti, intlist_dump li stampa tutti però tutti insieme
non singolarmente

Il giorno 11 febbraio 2016 23:00, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ah ho capito quello che dite!

Il giorno 11 febbraio 2016 23:04, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by TeoColuccio** [comment]
Così già credo vada meglio, ma io lo toglierei proprio quel intlist_dump()

Il giorno 11 febbraio 2016 23:06, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
invece è utile, piuttosto farei la stampa su una sola riga

**Comment by TeoColuccio** [comment]
Volevo mettere una virgola tra gli indici ma dopo finivano con una virgola:
15,

Il giorno 11 febbraio 2016 23:24, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
haha e non la mettere

Il giorno 11 febbraio 2016 23:33, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Eh infatti ahah

Il giorno 11 febbraio 2016 23:34, Fabio Z Tessitore <
notifications@github.com> ha scritto:
