### ISSUE TITLE
board_add_tile

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#15]
Scrivere la funzione board_add_tile che aggiunge una tessera in una posizione libera scelta a caso della board

**Comment by TeoColuccio** [comment]
Come faccia a scegliere una posizione a caso?

2016-02-11 23:44 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Cioè non ho un min e max..

Il giorno 11 febbraio 2016 23:48, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Ne sei sicuro?

Il giovedì 11 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Cioè ce l'ho ma poi devo vedere se la cella è libera o meno

Il giorno 11 febbraio 2016 23:52, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Avete visto l'abbozzo?

Il giovedì 11 febbraio 2016, Teodoro Coluccio teodoro.coluccio@gmail.com
ha scritto:

**Comment by FabioZTessitore** [comment]
si ho visto purtroppo ... hahaha
non ha né testa né coda

**Comment by TeoColuccio** [comment]
Vabbè qualcosa fa, sceglie una posizione a caso..

Il sabato 13 febbraio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Pure quello fa male

Il sabato 13 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Random_between non si usa così?

Il sabato 13 febbraio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Si

Il sabato 13 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Ok a come ho fatto io sceglie la posizione e finché è occupata sceglie un altro numero, per poi assegnare una tile

Inviato da iPad

**Comment by FabioZTessitore** [comment]
e la lista delle posizioni libere che ce l'hai a fare?

**Comment by TeoColuccio** [comment]
Eh peggio, che devo fare, controllare se il numero rand appartiene alla
lista pos_free?

2016-02-13 19:23 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
no, freepos contiene la lista delle posizioni libere. Devi scegliere quindi un numero tra questi. Pensaci un po'

**Comment by TeoColuccio** [comment]
Ahah ma non mi dite che è così: random_between(b->posfree.values[0],
b->pos_free.values[16])

2016-02-14 12:35 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
non proprio, la lista delle posizioni libere non è composta sempre da 16 elementi

**Comment by TeoColuccio** [comment]
Mi faccio tornare la lunghezza con la intlist_len, così il minimo rimane zero e il massimo sarà la lunghezza 

Inviato da iPad

**Comment by FabioZTessitore** [comment]
eh e poi?

**Comment by TeoColuccio** [comment]
Dovrei togliere quell'indice dalle celle libere e mettere la tile nel
puntatore a tile

2016-02-14 19:53 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
comincia ad estrarre la posizione libera, poi vediamo cosa fare con i puntatori ecc ecc

**Comment by FabioZTessitore** [comment]
immagina che siano libere le caselle 0 e 15.
freepos_len = 2
freepos = [0, 15]
in quale intervallo estrai il numero?

**Comment by TeoColuccio** [comment]
Eh ma l'intervallo sarà per forza  [0-15]... Come facciamo per scegliere
SOLO tra 0 e 15?!
PS domani non vengo a scuola sto influenzato al massimo

Il domenica 14 febbraio 2016, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
eh non arriviamo a capirci ...

la lista che ce l'hai a fare?

ps. non avevo letto il tuo messaggio e ti avevo portato il computer

**Comment by TeoColuccio** [comment]
Eh l'abbiamo per vedere le celle libere, ma non ho capito come usarla in
questo caso
ps. L'avete rimasto in lab?

Il lunedì 15 febbraio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
ti ripeto: hai una lista contenente due numeri, ad es [0, 13]
Ne devi scegliere uno.
Pensa bene a cosa estrarre

**Comment by TeoColuccio** [comment]
Mi viene da dire tra 0 e 1 perché sono 2 i numeri
Il 15 feb 2016 19:44, "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
eh avanti

**Comment by TeoColuccio** [comment]
Adesso ho capito questo passaggio. Il prossimo passo è quello di assegnare
t al vettore di puntatori di indice rand. E poi dovrei togliere
quell'indice dalle celle libere.

2016-02-15 20:13 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
avrai anche capito, ma non è quello che dice il tuo codice

**Comment by TeoColuccio** [comment]
Ma quel "eh avanti" di prima per cosa stava? Io l'ho preso per un va bene
ahah

Il giorno 15 febbraio 2016 21:55, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
infatti, sembrava che avessi capito a parole. Il codice dice altro invece

**Comment by TeoColuccio** [comment]
Allora: libere le caselle 0 e 15.
freepos_len = 2
freepos = [0, 15]

per scegliere il numero: il minimo è sicuro 0 ed il max non è 2 ma sarà 2-1
così i casi saranno 0 e 1

2016-02-15 22:11 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma non è quello che fa il tuo codice

**Comment by TeoColuccio** [comment]
min è 0 e max len -1! Non è così?

2016-02-15 22:18 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
si, ma non è quello che hai scritto

ti ricordo che io vedo quello che hai pushato

**Comment by TeoColuccio** [comment]
Prof io questo vedo dal sito

2016-02-15 22:28 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
questo è quello che vedo io:

``` c
rand = random_between(b->pos_free.values[0], b->pos_free.values[len-1]);
```

non mi sembra che tu stia estraendo un numero compreso tra 0 e len-1

**Comment by TeoColuccio** [comment]
Avevo rimasto 0 e len-1 nell'indice..

2016-02-15 22:36 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
mo' ragioniamo.
ti ricordo che random_between estrae numeri compresi tra min incluso e max escluso

**Comment by TeoColuccio** [comment]
Ah già allora dovrei togliere il -1

2016-02-15 22:46 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
si.
poi andiamo ai fatti importanti.
la funzione board_add_tile deve creare la tile (allocazione dinamica visto che non esiste), e richiamare la funzione board_set per piazzarla sulla board

**Comment by TeoColuccio** [comment]
L'allocazione dinamica dovrebbe essere giusta, sulla set ho dei dubbi e
comunque non ho messo free().

Il giorno 15 febbraio 2016 22:53, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ci siete?

Il giorno 15 febbraio 2016 23:12, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Ci sono alcune piccole modifiche da fare. Dopo aver creato la file bisogna
assegnarle un valore random 2 o 4. Vedi tile.h per capire quale funzione fa
al caso tuo.
Al termine di board_add_tile bisogna aggiornare la lista delle posizioni
libere.
Random_init non va richiamata qui ma dovresti cominciare a scrivere un main
che crea la board e aggiunge tessere per vedere se il tutto funziona.
Inoltre avendo fatto allocazione dinamica vedi creare una funzione
board_destroy per ripulire la memoria

Ps i lab sono inagibili per infiltrazioni di acqua

Il lunedì 15 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Allora iniziamo con l'assegnare un valore ad una tile: posso usare la
tile_make

Il giorno 16 febbraio 2016 09:37, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Però tile_make ne crea un'altra di tile

Il giorno 16 febbraio 2016 20:30, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
si però non fa allocazione dinamica. tile_make crea una tile nella funzione e poi ne restituisce una copia, che puoi copiare nella tile che hai creato tu

**Comment by TeoColuccio** [comment]
Per scegliere il numero tra 2 e 4 userò random_between() tra 0 e 2. Se esce
0 metterà 2 altrimenti 4. Va bene come ragionamento?

Il giorno 16 febbraio 2016 21:47, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
ovviamente no, così hanno il 50% di possibilità ognuno. Invece il 4 deve
avere solo il 10% di possibilità di uscita

Il giorno 16 febbraio 2016 22:19, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Queto ancora non lo sapevo.. allora tra 0 e 11

Il giorno 16 febbraio 2016 22:21, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ho fatto, però, perchè se metto tile = tile_make(4) senza \* davanti tile
dice che sono due formati diversi?

Il giorno 16 febbraio 2016 22:49, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
perché tile_make restituisce la copia di una tile (Tile), mentre tile è una Tile*

**Comment by TeoColuccio** [comment]
Eh ma se metto il \* che succede?

2016-02-16 23:34 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Tu hai definito tile in questo modo:

``` c
Tile *tile;
```

quindi tile è un puntatore a Tile (contiene indirizzo).
Invece `*tile` è proprio la tile puntata dal puntatore `tile`

**Comment by FabioZTessitore** [comment]
per il momento va bene così. Poi facciamo altri aggiustamenti. Fai le altre cose che avevo scritto in precedenza

**Comment by TeoColuccio** [comment]
Ok capito.

Il giorno 16 febbraio 2016 23:38, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ma per quanto riguarda la tile allocata dinamicamente, devo deallocare la
memoria con free.. come la vado a pescare visto che appartiene
escusivamente ad un'altra funzione?

Il giorno 16 febbraio 2016 23:39, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Non c'entra dove è stata allocata. Hai la board con i puntatori

Il martedì 16 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Ma non posso puntare a tile

Il giorno 16 febbraio 2016 23:45, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ok forse ho trovato

Il giorno 16 febbraio 2016 23:49, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Ma come no?

Il martedì 16 febbraio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Adesso non va bene?

Il giorno 16 febbraio 2016 23:50, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
add_tile non accetta come parametro una tile. la crea lei

**Comment by FabioZTessitore** [comment]
inoltre l'aggiornamento delle posizioni libere non lo fai, continui a fare sta stampa inutile hahaha

**Comment by TeoColuccio** [comment]
Per aggiornare le pos libere: come lo tolgo un elemento da una lista??

2016-02-17 14:19 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
quando abbiamo creato la lista di interi non abbiamo previsto questa possibilità. L'idea era che era più facile ricreare la lista daccapo piuttosto che mettersi a fare queste operazioni

**Comment by TeoColuccio** [comment]
La ricreo e ci devo mettere pure i valori dentro

Il giorno 17 febbraio 2016 18:56, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Non la ricrei. È allocata insieme alla board. La azzeri e rimetti i valori

Il mercoledì 17 febbraio 2016, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Escludendo quelli adesso occuppati

Il giorno 17 febbraio 2016 19:54, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Qualcosa già funziona

Il giorno 17 febbraio 2016 19:54, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ora funziona, ma la stampa fa parte board_dump mentre la nuova lista è di
board_add_tile

Il giorno 17 febbraio 2016 20:08, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
l'aggiornamento della lista delle celle vuote non va bene. Così facendo dici che sono tutte vuote tranne quella dove hai inserito l'ultima tile

**Comment by TeoColuccio** [comment]
Eh allora come posso fare, lo faccio in base a quante celle puntano a null?

Inviato da iPad

**Comment by FabioZTessitore** [comment]
vediamo cosa hai in mente

**Comment by TeoColuccio** [comment]
Qui (forse) potete chiudere
