### ISSUE TITLE
board_destroy

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#16]
le tile vanno liberate singolarmente (solo se ci sono ovviamente)

**Comment by TeoColuccio** [comment]
Perchè se provavo a liberare tutto insieme usciva quella roba?

2016-02-17 14:17 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma scusa, le allochi una alla volta, le liberi una alla volta. Una singola cella è un puntatore che punta alla tile allocata
