### ISSUE TITLE
board_move_tile

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#18]
board_move_tile sposta una tile da una posizione di partenza a una di arrivo

**Comment by TeoColuccio** [comment]
Ho abbozzato qualcosa

2016-02-21 13:10 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
meglio del previsto, ma perché solo un'istruzione nell'if e non tutte e tre?

**Comment by TeoColuccio** [comment]
Eh già

2016-02-22 19:57 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Ora va bene?

Il martedì 23 febbraio 2016, Teodoro Coluccio teodoro.coluccio@gmail.com
ha scritto:

**Comment by TeoColuccio** [comment]
Ci siete?

Il giorno 23 febbraio 2016 21:11, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
per i nostri scopi può andar bene.
A voler fare le cose meglio io farei un controllo sulla destinazione, perché se c'è già una Tile significa che il gioco non sta funzionando bene ed è un errore grave.
Inoltre per fare lo spostamento vero e proprio si potrebbero usare le funzioni set e get che hai definito precedentemente.

**Comment by FabioZTessitore** [comment]
ci proviamo a usare set e get?

**Comment by TeoColuccio** [comment]
Dovrebbe andare, comunque esce un warning nel momento in cui assegno il
valore null alla tile di origine.

2016-02-26 20:47 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
riga 94, hai messo == invece di =

**Comment by FabioZTessitore** [comment]
potresti usare get() ogni volta che fai l'accesso ad una tile all'interno di board

**Comment by TeoColuccio** [comment]
Fatto

2016-02-27 22:09 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Ma per curiosità, se mettevo == al posto di = che cambiava? Ahah

Il giorno 28 febbraio 2016 11:18, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
== è una comparazione. Ti dice se è vero o falso.
= è un'assegnazione

**Comment by FabioZTessitore** [comment]
ti sei sprecato, puoi usare ancora una set e una get

**Comment by TeoColuccio** [comment]
La set la posso usare per mettere il valore NULL nell'indice di origine, ma
poi è finita la funzione, la get dove la metto?

Il giorno 28 febbraio 2016 12:52, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
guarda bene

**Comment by TeoColuccio** [comment]
Ora credo potete chiudere

2016-02-28 18:03 GMT+01:00 Fabio Z Tessitore notifications@github.com:
