### ISSUE TITLE
Intlist push: implementare controlli

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#2]
Bisogna implementare un controllo affinché non sia possibile inserire altri elementi se la lista è piena

**Comment by TeoColuccio** [comment]
Fatto

2016-01-20 20:46 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma non dire sciocchezze. che controllo è? size sarà sempre maggiore di zero

**Comment by TeoColuccio** [comment]
Sugli schizzi che mi avete fatto non sta segnato, ma size rappresenta le
celle libere?

Il giorno 21 gennaio 2016 21:40, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
no, size significa dimensione. Rappresenta quelle occupate. in altre parole è la lunghezza della lista

**Comment by TeoColuccio** [comment]
Una soluzione allora può essere "if size <= 16" perchè 16 sono quelle in
totale.

Il giorno 21 gennaio 2016 21:49, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
quasi ma ci sei

**Comment by TeoColuccio** [comment]
Mica devo togliere "=" ?

2016-01-21 22:01 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
eh

**Comment by TeoColuccio** [comment]
Fatto

2016-01-21 22:06 GMT+01:00 Fabio Z Tessitore notifications@github.com:
