### ISSUE TITLE
board_rotate

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#20]
Creare la funzione board_rotate che ruota di novanta gradi la scacchiera

**Comment by TeoColuccio** [comment]
Ho creato un file matrice .c per testare la funzione

**Comment by TeoColuccio** [comment]
So invertire gli elementi partendo dal 15 fino a zero ed è facile, ma a
ruotare non so..

Il giorno 6 marzo 2016 19:37, Teodoro Coluccio teodoro.coluccio@gmail.com
ha scritto:

> Ho creato un file matrice .c per testare la funzione
