### ISSUE TITLE
IntList Dump

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#3]
La funzione non stampa gli elementi presenti nella lista

**Comment by TeoColuccio** [comment]
Ho creato un file main di prova ma non va, forse sta qualcosa errato nel
make

2016-01-20 20:46 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
certo, nel Makefile non c'è traccia di main

**Comment by TeoColuccio** [comment]
Ho modificato, credo di aver fatto bene

2016-01-21 22:29 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ok il makefile, dovrebbe compilare
rimane il problema sulla funzione dump

prova a scrivere un main di prova, cosa ti stampa?

**Comment by TeoColuccio** [comment]
E' quello che sto facendo, ma mi dà errori di link

Il giorno 21 gennaio 2016 22:45, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
prova a includere il file .h invece del file .c nel main :-1:

**Comment by TeoColuccio** [comment]
Oddio!!!! Ahahahahah

2016-01-21 22:52 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Comunque non andrebbero tutti azzerati gli elementi?

Il giorno 21 gennaio 2016 22:52, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
non è necessario

**Comment by TeoColuccio** [comment]
No però non ho capito perchè non stampa gli elementi...

2016-01-21 23:07 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
il problema è che li stampa

**Comment by TeoColuccio** [comment]
Mica li deve ritornare?!

2016-01-21 23:19 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
no, stampare

**Comment by TeoColuccio** [comment]
Ma così si stampa un vettore

2016-01-21 23:21 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
che è un vettore lo sai tu. Per il resto del mondo è una lista e tu devi fare in modo che vengano stampati solo gli elementi presenti

**Comment by FabioZTessitore** [comment]
sei fantasioso ma non va bene. non c'è lo zero come terminatore (non è una stringa). Inolte lo zero è un valore valido

**Comment by TeoColuccio** [comment]
Secondo me la stampa va bene, devo rivedere la condizione

2016-01-22 0:25 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
E rivedi

Il venerdì 22 gennaio 2016, Teodoro notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Sto rivedendo, ma non capisco dove sia l'errore..

2016-01-22 16:47 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma aggiusti una cosa e ne rompi un'altra.
poniti la domanda: quanti elementi del vettore devo stampara? e fallo

**Comment by TeoColuccio** [comment]
Più facile del previsto..

2016-01-22 20:43 GMT+01:00 Fabio Z Tessitore notifications@github.com:
