### ISSUE TITLE
Modulo random

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#4]
Bisogna creare un modulo random con le funzioni init() e between().
Init() inizializza il sistema di generazione dei numeri pseudocasuali.
between() restituisce un intero compreso tra un minimo e un massimo

**Comment by TeoColuccio** [comment]
Ma il numero non che deve essere scelto tra {2, 4}?

2016-01-20 20:51 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
La funzione ha utilizzo generale. Per ora ci serve per estrarre una delle posizioni libere.
Concentrati sul compito che deve avere: estrarre un numero compreso tra un minimo e un massimo

**Comment by TeoColuccio** [comment]
Se ho capito bene:
- in init() inizializzo il seed.
- in between() mi da il numero compeso tra un minimo e massimo. Il minimo è
  0 e il massimo 16

Il giorno 21 gennaio 2016 22:30, Fabio Z Tessitore <notifications@github.com

**Comment by TeoColuccio** [comment]
Aspettate: random da che è formato?!?!

Il giorno 23 gennaio 2016 19:06, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
il modulo random non contiene strutture dati. Solo funzioni di utilità

Il giorno 23 gennaio 2016 19:14, Teodoro notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
2 cose:
-Ovviamente sbaglio nell'inizializzare il seme;
-Perchè su con dev bastava includere solo stdlib mentre qui se non includo
anche time.h esce un warning?

Il giorno 23 gennaio 2016 19:18, Fabio Z Tessitore <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> ha scritto:

**Comment by FabioZTessitore** [comment]
Le funzioni dovrebbero avere un nome che specifichi a quale modulo appartengono. Qui le classi non ci sono ricorda

**Comment by FabioZTessitore** [comment]
Riguardo ai file di intestazione ... dovremmo chiederci perché dev non segnala nulla. Mah

**Comment by FabioZTessitore** [comment]
Infine la funzione between non fa quello che dice

**Comment by TeoColuccio** [comment]
comunque non sbagliavo nell'inizializzazione, mi ero solo dimenticato di
chiamare init nel main

2016-01-23 19:49 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Una cosa che non ho mai capito bene nel generare un numero random è perchè
se non inizializziamo esce sempre lo stesso numero?

Il giorno 24 gennaio 2016 11:17, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Come può una macchina deterministica generare numeri veramente casuali?
I pc generano numeri pseudo-casuali in base ad un algoritmo. Tale algoritmo estrae la sequenza in base ad un seme. Quello che fai nell'inizializzazione è generare un seme non prevedibile (il tempo al momento di esecuzione) in modo da avere una sequenza non prevedibile in anticipo.

Riguardo al codice, ti ricordo che quando si estrae un numero compreso tra min e max, min è incluso, ma max è escluso. Devi aggiustare questa cosa

**Comment by TeoColuccio** [comment]
Se all'ultimo metto min + 1 non risolvo?

Il giorno 24 gennaio 2016 11:28, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
dovresti scrivere un file di test per il modulo

``` c
/* mi aspetto che stampi 10 volte il numero 30 */
for (i=0; i<10; i++) {
  printf("%d\n", random_between(30, 31));
}

/* mi aspetto che stampi 30 o 31, 10 volte */
for (i=0; i<10; i++) {
  printf("%d\n", random_between(30, 32));
}
```

poi in base ai risultati del test fai le modifiche e rifai i test

**Comment by TeoColuccio** [comment]
Adesso va bene

2016-01-24 11:56 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
adesso fa quello che deve. Due note
1. non sono necessarie tre righe di codice, ne basta una
2. non serve l'inclusione di stdio.h

**Comment by TeoColuccio** [comment]
C'era un file + che credo sia stato creato per errore e l'ho eliminato.
Comunque se elimino stdlib mi da due warning perchè srand e rand sono
dichiarate in essa, ma alla fine funziona

Il giorno 26 gennaio 2016 16:39, Fabio Z Tessitore <notifications@github.com
