### ISSUE TITLE
Tile dump

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#7]
Creare la funzione dump per la stampa di debug di una Tile

**Comment by TeoColuccio** [comment]
Cosa si intende per stampa di debug?

Il sabato 30 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
una stampa senza troppi fronzoli, solo per vedere se è tutto ok

**Comment by TeoColuccio** [comment]
Ma se la tile è solo un intero, che altro ci sta  da stampare?

Il giorno 30 gennaio 2016 16:19, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Siccome è una stampa di debug (cioè non va al pubblico ma allo/agli
sviluppatori) si possono inserire tutte le informazioni utili.
In questo caso più che stampare "tile: 2" non c'è altro. Però nota la
parola "tile" (che ovviamente può essere sostituita con quello che ti
pare), nel gioco non deve comparire. Invece in fase di debug può essere
utile per capire quel 2 a chi si riferisce

2016-01-31 11:19 GMT+01:00 Teodoro notifications@github.com:

**Comment by TeoColuccio** [comment]
Capito

Il giorno 31 gennaio 2016 11:25, Fabio Z Tessitore <notifications@github.com

**Comment by TeoColuccio** [comment]
Ritorna una stringa o faccio un printf direttamente?

Il giorno 31 gennaio 2016 11:28, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Falla stampare

**Comment by FabioZTessitore** [comment]
Siccome è una funzione di debug non dovresti fidarti del puntatore che ti arriva come parametro.
Inoltre siccome la board sarà composta da un vettore di TilePtr (non tutti con una Tile associata) potrebbe essere utile fare un controllo. Se il puntatore punta veramente ad una Tile ne stampi il valore altrimenti stampi la stringa "NULL"

**Comment by TeoColuccio** [comment]
Non ho capito bene la condizione che devo mettere

Il giorno 31 gennaio 2016 12:11, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Il puntatore t punta veramente a qualcosa? Oppure no?

Il giorno 31 gennaio 2016 12:35, Teodoro notifications@github.com ha
scritto:
