### ISSUE TITLE
Tile make

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#8]
Creare la funzione make per la creazione di una Tile

**Comment by TeoColuccio** [comment]
La tile come si deve generare?

2016-01-30 15:58 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Ti basta creare una nuova Tile nella funzione make, con associato un
valore, e restituirla (verrà fatta una copia, ma contenendo un solo intero
non è un problema)

2016-01-31 11:30 GMT+01:00 Teodoro notifications@github.com:

**Comment by TeoColuccio** [comment]
Eh ma il valore lo scelgo io?

Il giorno 31 gennaio 2016 11:32, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Ovviamente no. La Tile che stai creando non sa a che gioco sta giocando. Ti trovi?
Allora è meglio creare un meccanismo che sia riutilizzabile. Di quale informazione hai bisogno per creare una Tile? Un valore intero ... E passalo come parametro alla funzione

**Comment by FabioZTessitore** [comment]
La funzione make che hai creato è tecnicamente corretta, ma volevo farti vedere un'altra tecnica.
Prova a riscriverla con questo prototipo:

``` c
Tile tile_make(int value);
```

**Comment by TeoColuccio** [comment]
Va bene il t->num = value?

2016-01-31 12:13 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
eh no, cambia tutta la struttura. Devi creare una Tile, metterci il numero
e restituirla

2016-01-31 12:20 GMT+01:00 Teodoro notifications@github.com:

**Comment by TeoColuccio** [comment]
Ah sì

Il giorno 31 gennaio 2016 12:27, Fabio Z Tessitore <notifications@github.com
