### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/2048#9]
Evita di caricare anche l'eseguibile

**Comment by FabioZTessitore** [comment]
questa issue qui non ti piaceva?

**Comment by TeoColuccio** [comment]
Adesso dovrebbe andare

2016-01-31 19:40 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
penso di si, però elimina il file eseguibile che hai caricato in precedenza

**Comment by TeoColuccio** [comment]
Okk

2016-02-01 20:55 GMT+01:00 Fabio Z Tessitore notifications@github.com:
